CREATE DATABASE FUNDDATA;
USE FUNDDATA;

CREATE TABLE IF NOT EXISTS `DAILY_NET_VALUE`(
    `REPORT_DATE` DATE NOT NULL,
    `FUND_ID` VARCHAR(10) NOT NULL,
    `UNIT_NET_VALUE` DOUBLE,
    `ACCU_NET_VALUE` DOUBLE,
    `SUBSCRIPTION` VARCHAR(10),
    `REDEMPTION` VARCHAR(10),
    `BONUS_PER_SHARE` DOUBLE,
    PRIMARY KEY (REPORT_DATE, FUND_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ASSET_ALLOCATION`(
    `REPORT_DATE` DATE NOT NULL,
    `FUND_ID` VARCHAR(10) NOT NULL,
    `STOCK_PROP` DOUBLE,
    `BOND_PROP` DOUBLE,
    `CASH_PROP` DOUBLE,
    `NET_ASSET_VALUE` DOUBLE,
    PRIMARY KEY (REPORT_DATE, FUND_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `HOLDER_STRUCTURE`(
    `REPORT_DATE` DATE NOT NULL,
    `FUND_ID` VARCHAR(10) NOT NULL,
    `INST_PROP` DOUBLE,
    `INDI_PROP` DOUBLE,
    `INTE_PROP` DOUBLE,
    `TOTAL_SHARE` DOUBLE,
    PRIMARY KEY (REPORT_DATE, FUND_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `FUND_RATING`(
    `REPORT_DATE` DATE NOT NULL,
    `FUND_ID` VARCHAR(10) NOT NULL,
    `ZSPJ` INTEGER,
    `SZPJ3` INTEGER,
    `SZPJ5` INTEGER,
    `JAPJ` INTEGER,
    PRIMARY KEY (REPORT_DATE, FUND_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `BOND_HOLDINGS`(
    `REPORT_DATE` DATE NOT NULL,
    `FUND_ID` VARCHAR(10) NOT NULL,
    `BOND_ID` VARCHAR(10) NOT NULL,
    `BOND_NAME` VARCHAR(20),
    `BOND_SPEC_PROP` DOUBLE,
    `BOND_SPEC_VALUE` DOUBLE,
    PRIMARY KEY (REPORT_DATE, FUND_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `STOCK_HOLDINGS`(
    `REPORT_DATE` DATE NOT NULL,
    `FUND_ID` VARCHAR(10) NOT NULL,
    `STOCK_ID` VARCHAR(10)  NOT NULL,
    `STOCK_NAME` VARCHAR(20),
    `STOCK_SPEC_PROP` DOUBLE,
    `STOCK_SPEC_SHARE` DOUBLE,
    `STOCK_SPEC_VALUE` DOUBLE,
    PRIMARY KEY (REPORT_DATE, FUND_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `SECTOR_ALLOCATION`(
    `REPORT_DATE` DATE NOT NULL,
    `FUND_ID` VARCHAR(10) NOT NULL,
    `SECTOR_CODE` VARCHAR(5),
    `SECTOR_NAME` VARCHAR(40),
    `SECTOR_ASSET_VALUE` DOUBLE,
    `SECTOR_PROP` DOUBLE,
    PRIMARY KEY (REPORT_DATE, FUND_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;